### ISSUE TITLE
cargo-concordium: Double printing of warning messages during build with schema embedded

### ISSUE THREAD

**Issue by rimbi** [Concordium/concordium-wasm-smart-contracts#48]
**Description**

When the `--schema-embed` parameter is used with `cargo concordium build` if there are warnings in the contract they are printed twice. 

**Steps to Reproduce**

- Create a smart contract such that `rustc` prints a compile-time warning message.
- Build the contract with `cargo concordium build --embed-schema`

**Expected Result**
- 1 warning message

**Actual Result**
- 2 warning messages

**Versions**
- Software Version: 3.0
- OS: Any

**Comment by abizjak** [comment]
Yes. This is because the contract has to be built in two ways, first as a normal contract, and then second time to emit the schema.

The only option we'd have is to suppress output from the second build. However this is problematic in the cases where there are issues. Suppressing input unless the build succeeds could be on option, but needs some analysis to make sure that warnings don't sometimes contain critical information.

**Comment by rimbi** [comment]
Suppressing only the output from the second `cargo build` seems to be a viable solution.

**Comment by abizjak** [comment]
Since we are not confident that this will not sometimes hide important warnings, the benefit of doing this does not outweigh the risks.

So I am closing this issue.
